version: "3.0"

services:
        petclinic:
                image: hirendrakoche/petclinic:$BUILD_TAG
                ports:
                - "8081:8080"
                networks:
                - petclinic

networks:
        petclinic:
