kind: Namespace
apiVersion: v1
metadata:
    name: petclinic

---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: petclinic
    namespace: petclinic
    labels:
        app: petclinic
        env: dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: petclinic
            env: dev
    template:
        metadata:
            name: petclinic
            labels:
                app: petclinic
                env: dev
        spec:
            containers:
                - name: petclinic
                  image: petclinic:BUILD
                  imagePullPolicy: IfNotPresent
                  resources: {}
                  ports:
                    - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
    name: petclinic-svc
    labels:
        app: petclinic
        env: dev
    namespace: petclinic
spec:
    type: ClusterIP
    selector:
        app: petclinic
        env: dev
    ports:
        - port: 8080
          targetPort: 8080
          protocol: TCP


---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: petclinic-ingress
  namespace: petclinic
 # annotations:
 #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /petclinic
            pathType: ImplementationSpecific
            backend:
              service:
                name: petclinic-svc
                port:
                    number: 8080     


