kind: Namespace
apiVersion: v1
metadata:
    name: petclinic

---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: petclinic
    namespace: petclinic
    labels:
        app: petclinic
        env: dev
spec:
    replicas: 2
    selector:
        matchLabels:
            app: petclinic
            env: dev
    template:
        metadata:
            name: petclinic
            labels:
                app: petclinic
                env: dev
        spec:
            containers:
                - name: petclinic
                  image: petclinic:BUILD
                  resources: {}
                  ports:
                    - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
    name: petclinic-svc
spec:
    type: LoadBalancer
    selector:
        app: petclinic
        env: dev
    ports:
        - port: 8080
          targetPort: 8080


