version: 2.0
jobs:
    build:
        docker:
            - image: maven:3.5.0

        steps:
            - checkout
            - run:
                name: Build code
                command:
                    mvn clean package

            - store_artifacts:
                path: target/petclinic.war
            
            - store_test_results:
                path: target/surefire-reports/
