version: 2.0
jobs:
    petclinic:
        docker:
            - image: maven:latest

        steps:
            - checkout
            - run:
                name: Build code
                command:
                    mvn clean package
