version: 2.1
jobs:
    PetClinic:
        docker:
            - image: maven:latest    
        steps:
            - checkout
            - run:
                name: Build code
                command:
                    mvn clean package
